# Docker
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Git Merge"
      git remote add microsoft/fhir-server https://github.com/microsoft/fhir-server.git
      git remote -v
      git fetch microsoft/fhir-server
      git checkout origin
      git merge microsoft/fhir-server/master
      git push origin master
      
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/build/docker/Dockerfile'
        tags: |
          $(tag)